(()=>{'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=960,H=540,FLOOR_Y=426;
const $=s=>document.querySelector(s),overlay=$('#overlay'),menu=$('#menu'),hud=$('#hud'),bossHud=$('#bossHud'),toast=$('#toast');
const heroes=[{name:'BUENO',job:'SUPORTE',desc:'Chicote · alcance',color:'#ff625e',dark:'#222b35',boss:'IMPRESSORA COLOSSAL',world:'SALA DE SUPORTE',enemy:'IMPRESSORA',shot:'▤',special:'PULSO VERMELHO'}, {name:'VAZ',job:'REDES',desc:'Feixes · distância',color:'#55d8cc',dark:'#243a4a',boss:'RJ • REI DOS CABOS',world:'DATA CENTER',enemy:'CABO VIVO',shot:'⌁',special:'BANDA LARGA'}, {name:'RITT',job:'DADOS & CÓDIGO',desc:'Código · combos',color:'#a0e879',dark:'#243b32',boss:'ESPECTRO ALGORÍTMICO',world:'MATRIZ DE DADOS',enemy:'USUÁRIO SEM CHAMADO',shot:'{ }',special:'QUERY FINAL'}];
heroes.push({name:'ELLI',job:'NEON',desc:'Voo · golpes guiados',color:'#ff49b9',dark:'#402034',boss:'GUARDIÃO',world:'ÁREA SECRETA',enemy:'SENTINELA',shot:'✦',special:'EXPLOSÃO NEON',secret:true});
let nickname='',score=0,runActive=false,levelStartScore=0,awardedLevels=new Set(),ranking=[];
const rankingKey='tech-titans-ranking-v1';
try{const saved=JSON.parse(localStorage.getItem(rankingKey)||'[]');if(Array.isArray(saved))ranking=saved.filter(r=>r&&typeof r.name==='string'&&r.name.trim()&&r.name.length<=20&&Number.isSafeInteger(r.score)&&r.score>=0).sort((a,b)=>b.score-a.score)}catch{}
function renderRanking(){const box=$('#ranking');box.classList.toggle('hidden',screen!=='title');const list=$('#rankingList');list.innerHTML='';ranking.slice(0,3).forEach((r,i)=>{const row=document.createElement('li'),name=document.createElement('span'),points=document.createElement('b');name.textContent=(i+1)+'. '+r.name;points.textContent=r.score+' pts';row.append(name,points);list.append(row)});if(!ranking.length){const row=document.createElement('li');row.textContent='Seja o primeiro a pontuar!';list.append(row)}}
function saveRun(){if(!runActive)return;runActive=false;const existing=ranking.find(r=>r.name.toLocaleLowerCase('pt-BR')===nickname.toLocaleLowerCase('pt-BR'));if(existing){if(score>existing.score){existing.score=score;existing.name=nickname}}else ranking.push({name:nickname,score});ranking.sort((a,b)=>b.score-a.score);try{localStorage.setItem(rankingKey,JSON.stringify(ranking))}catch{} }
function addScore(points){if(!runActive||player?.dead)return;score+=points;$('#scoreValue').textContent=score}
function showNickname(){if(heroLocked()){menu.querySelector('#secretCode').focus({preventScroll:true});return}screen='nickname';keys={};$('.panel').classList.remove('selecting');$('.panel h1').textContent='SEU APELIDO';$('.lead').textContent='Digite seu apelido para entrar no ranking.';$('.hint').textContent='ENTER começar · ESC voltar';menu.innerHTML='<form id="nicknameForm"><label for="nickname">APELIDO</label><input id="nickname" maxlength="20" required autocomplete="nickname" placeholder="Seu apelido"><button type="submit">COMEÇAR</button></form><button type="button" id="nicknameBack">VOLTAR</button>';const input=$('#nickname');input.value=nickname;$('#nicknameForm').onsubmit=e=>{e.preventDefault();const value=input.value.trim();if(!value){input.setCustomValidity('Digite seu apelido.');input.reportValidity();return}nickname=value;startGame()};input.oninput=()=>input.setCustomValidity('');$('#nicknameBack').onclick=showSelect;input.focus({preventScroll:true})}
function showGameOver(){saveRun();screen='gameover';keys={};paused=false;transition=0;toastTimer=0;toast.classList.add('hidden');$('#pause').classList.add('hidden');hud.classList.add('hidden');bossHud.classList.add('hidden');overlay.classList.remove('hidden');$('.panel').classList.remove('selecting');$('.panel h1').textContent='GAME OVER';$('.lead').textContent=nickname+' · '+score+' pontos';$('.hint').textContent='ENTER voltar ao início';menuIndex=0;setMenu(['VOLTAR AO INÍCIO'],showTitle);menu.querySelector('button').focus({preventScroll:true})}
let secretUnlocked=false;
function heroLocked(){return !!heroes[hero].secret&&!secretUnlocked}
function unlockSecret(value){let password=value.trim().toLocaleLowerCase('pt-BR');if(password!=='chata'&&password!=='linda'){menu.querySelector('.secret-status').textContent='Código inválido';return false}secretUnlocked=true;renderHeroChoices();return true}
const levelNames=['Primeiro chamado','Fila de impressão','Papel atolado','Chefe: área crítica','Patch de conexão','Rota alternativa','Pacotes perdidos','Chefe: cabo mestre','Query inicial','Planilha infinita','Erro fatal','Chefe: código vivo'];
let screen='title',hero=0,level=0,menuIndex=0,player,enemies=[],shots=[],particles=[],heartPickups=[],attackVfx=[],platforms=[],camera=0,keys={},last=performance.now(),paused=false,pauseIndex=0,transition=0,worldWidth=2300,toastTimer=0, boss=null, audioCtx,specialCharge=0;
const backgroundImage=new Image();backgroundImage.src='Img/background-datacenter.png';const buenoSpriteSheet=new Image();buenoSpriteSheet.src='Img/bueno-spritesheet.png';const vazSpriteSheet=new Image();vazSpriteSheet.src='Img/vaz-spritesheet.png';const rittSpriteSheet=new Image();rittSpriteSheet.src='Img/ritt-spritesheet.png';
const buenoAttackSheet=new Image();buenoAttackSheet.src='Img/bueno-normal-attack.png';
// Separate silhouettes with wider space for the whip above the feet.
const buenoAttackFrames=[
{left:0,right:240,topLeft:0,topRight:240,anchor:112},
{left:240,right:475,topLeft:240,topRight:475,anchor:347},
{left:475,right:685,topLeft:475,topRight:775,anchor:575},
{left:685,right:1020,topLeft:775,topRight:1110,anchor:814},
{left:1020,right:1370,topLeft:1110,topRight:1435,anchor:1143},
{left:1380,right:1685,topLeft:1435,topRight:1730,anchor:1500},
{left:1685,right:1950,topLeft:1730,topRight:1950,anchor:1800},
{left:1950,right:2172,topLeft:1950,topRight:2172,anchor:2052}
];
function drawBuenoNormalAttack(p,scale){if(!buenoAttackSheet.complete||!buenoAttackSheet.naturalWidth)return false;let frame=buenoAttackFrames[Math.min(7,Math.floor((p.animClock||0)*16))],ratio=82/225*(p.crouch&&p.ground?.82:1);ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);ctx.scale((p.face<0?-1:1)*scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;ctx.scale(ratio,ratio);ctx.translate(-frame.anchor,-541);ctx.beginPath();ctx.moveTo(frame.topLeft,180);ctx.lineTo(frame.topRight,180);ctx.lineTo(frame.topRight,425);ctx.lineTo(frame.right,460);ctx.lineTo(frame.right,550);ctx.lineTo(frame.left,550);ctx.lineTo(frame.left,460);ctx.lineTo(frame.topLeft,425);ctx.closePath();ctx.clip();ctx.drawImage(buenoAttackSheet,0,0);ctx.restore();return true}
const buenoBossSheet=new Image();buenoBossSheet.src='Img/bueno-boss-spritesheet.png';
const printerColumns=[166,332,498,665,832,1001,1170,1338,1515];
function printerRow(y,h){return printerColumns.slice(0,-1).map((x,i)=>({x:x+12,y,w:printerColumns[i+1]-x-24,h,anchor:(x+printerColumns[i+1])/2}))}
const printerFrames={idle:printerRow(24,139),walkRight:printerRow(185,142),walkLeft:printerRow(353,145),shoot:printerRow(687,150),melee:[166,359,545,738,931,1115].map((x,i)=>({x:x+7,y:520,w:[359,545,738,931,1115,1297][i]-x-14,h:143,anchor:[260,441,628,816,1005,1206][i]}))};
const paperColumns=[166,256,350,446,542,642,738,833,931,1028,1124,1223,1323,1425,1515];
function drawPrinterBoss(){if(!buenoBossSheet.complete||!buenoBossSheet.naturalWidth)return false;let name=boss.anim||'idle',frames=printerFrames[name],action=name==='melee'||name==='shoot',index=Math.floor(boss.animClock*(action?12:name==='idle'?4:8)),frame=frames[action?Math.min(index,frames.length-1):index%frames.length],ratio=boss.h/145;ctx.save();ctx.translate(boss.x+boss.w/2,boss.y+boss.h);if((name==='shoot'||name==='melee'||name==='idle')&&boss.face<0)ctx.scale(-1,1);if(boss.vulnerable>0){ctx.shadowColor='#ff625e';ctx.shadowBlur=16}ctx.drawImage(buenoBossSheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);ctx.restore();return true}
function drawPrinterPaper(shot){if(!buenoBossSheet.complete||!buenoBossSheet.naturalWidth)return false;let index=Math.floor((shot.age||0)*18)%(paperColumns.length-1),x=paperColumns[index]+5,w=paperColumns[index+1]-paperColumns[index]-10;ctx.save();ctx.translate(shot.x+shot.w/2,shot.y+shot.h/2);if(shot.vx<0)ctx.scale(-1,1);let size=shot.paperSize||54;ctx.drawImage(buenoBossSheet,x,875,w,103,-size/2,-size*25/54,size,size*50/54);ctx.restore();return true}
function updatePrinterBoss(dt){let b=boss;if(b.hp<=0)return;b.t+=dt;b.animClock+=dt;b.vulnerable=Math.max(0,b.vulnerable-dt);b.cooldown=Math.max(0,b.cooldown-dt);let distance=player.x+player.w/2-(b.x+b.w/2);if(b.anim==='melee'||b.anim==='shoot'){if(!b.fired&&b.animClock>=.25){b.fired=true;if(b.anim==='shoot'){let count=b.hp<=50?3:1;for(let i=0;i<count;i++)shots.push({x:b.face<0?b.x-32:b.x+b.w,y:b.y+62+(i-(count-1)/2)*24,w:32,h:24,vx:b.face*290,life:4,age:0,damage:1,color:'#ff625e',from:'enemy',vfxType:'printerPaper'})}else{let area={x:b.face<0?b.x-85:b.x+b.w-10,y:b.y+25,w:95,h:b.h-25};if(rect(area,player))hurtPlayer()}}if(b.animClock>=(b.anim==='melee'?.5:8/12)){b.anim='idle';b.animClock=0;b.cooldown=1.1}}else{b.face=distance<0?-1:1;if(b.cooldown===0){b.anim=Math.abs(distance)<170?'melee':'shoot';b.animClock=0;b.fired=false}else{let next=Math.abs(distance)>190?(b.face>0?'walkRight':'walkLeft'):'idle';if(next!==b.anim){b.anim=next;b.animClock=0}if(next!=='idle')b.x=clamp(b.x+b.face*45*dt,35,worldWidth-b.w-35)}}if(rect(player,b))hurtPlayer()}
const printerEnemySheet=new Image();printerEnemySheet.src='Img/bueno-enemies-spritesheet.png';
const smallPrinterColumns=[311,425,532,642,752,862,973,1085,1213];
function smallPrinterRow(y,h){return smallPrinterColumns.slice(0,-1).map((x,i)=>({x:x+8,y,w:smallPrinterColumns[i+1]-x-16,h,anchor:(x+smallPrinterColumns[i+1])/2}))}
const smallPrinterFrames={physical:{idle:smallPrinterRow(17,70),walkRight:smallPrinterRow(103,62),walkLeft:smallPrinterRow(182,62),attack:smallPrinterRow(411,62)},paper:{idle:smallPrinterRow(497,61),walkRight:smallPrinterRow(574,56),walkLeft:smallPrinterRow(644,53),attack:smallPrinterRow(852,54)}};
function movePhysicalPrinter(e){let dx=player.x+player.w/2-(e.x+e.w/2);if(Math.abs(dx)>2)e.face=Math.sign(dx);if(e.anim==='attack'&&e.animClock<.5){e.vx=0;return}if(Math.abs(dx)<=55){e.vx=0;return}e.vx=(e.face||1)*(e.type===2?.95:.75)}
function updateSmallPrinterAnimation(e,dt){e.animClock=(e.animClock||0)+dt;e.strikeCooldown=Math.max(0,(e.strikeCooldown||0)-dt);if(e.anim==='attack'&&e.animClock<.5){if(e.type!==1&&!e.strikeHit&&e.animClock>=.25){e.strikeHit=true;if(Math.abs(player.x+player.w/2-(e.x+e.w/2))<75&&Math.abs(player.y-e.y)<55)hurtPlayer()}return;}if(Math.abs(e.vx)>.12)e.face=Math.sign(e.vx);let next=Math.abs(e.vx)>.12?(e.vx<0?'walkLeft':'walkRight'):'idle';if(e.type!==1&&e.strikeCooldown===0&&Math.abs(player.x-e.x)<65&&Math.abs(player.y-e.y)<55){next='attack';e.face=player.x+player.w/2<e.x+e.w/2?-1:1;e.strikeCooldown=.9;e.strikeHit=false;e.vx=0}if(e.anim!==next){e.anim=next;e.animClock=0}}
const smallPrinterCutouts=new Map();
function smallPrinterCutout(frame){let key=frame.x+':'+frame.y;if(smallPrinterCutouts.has(key))return smallPrinterCutouts.get(key);let crop=document.createElement('canvas');crop.width=frame.w;crop.height=frame.h;let c=crop.getContext('2d',{willReadFrequently:true});c.drawImage(printerEnemySheet,frame.x,frame.y,frame.w,frame.h,0,0,frame.w,frame.h);let pixels;try{pixels=c.getImageData(0,0,frame.w,frame.h)}catch{return null}let data=pixels.data,visited=new Uint8Array(frame.w*frame.h),queue=[];function add(x,y){if(x<0||y<0||x>=frame.w||y>=frame.h)return;let i=y*frame.w+x,o=i*4;if(visited[i])return;visited[i]=1;if(data[o+3]===0||(data[o]<=16&&data[o+1]<=16&&data[o+2]<=16)){queue.push(i);data[o+3]=0}}for(let x=0;x<frame.w;x++){add(x,0);add(x,frame.h-1)}for(let y=0;y<frame.h;y++){add(0,y);add(frame.w-1,y)}for(let n=0;n<queue.length;n++){let i=queue[n],x=i%frame.w,y=Math.floor(i/frame.w);add(x-1,y);add(x+1,y);add(x,y-1);add(x,y+1)}c.putImageData(pixels,0,0);smallPrinterCutouts.set(key,crop);return crop}
function drawSmallPrinter(e){if(!printerEnemySheet.complete||!printerEnemySheet.naturalWidth)return false;let name=e.anim||'idle',physical=e.type!==1,sourceName=name,frames=smallPrinterFrames[physical?'physical':'paper'][sourceName],index=Math.floor((e.animClock||0)*(name==='idle'?1:name==='attack'?16:10)),frame=frames[name==='attack'?Math.min(7,index):index%(name==='idle'?2:frames.length)],ratio=e.h/62;ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h);if(!name.startsWith('walk')&&(e.face||Math.sign(e.vx)||1)<0)ctx.scale(-1,1);ctx.imageSmoothingEnabled=false;let cutout=smallPrinterCutout(frame);if(cutout)ctx.drawImage(cutout,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);else ctx.drawImage(printerEnemySheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);ctx.restore();return true}
const vazBossSheet=new Image();vazBossSheet.src='Img/vaz-boss-spritesheet.png';
function cableRow(columns,y,h){return columns.slice(0,-1).map((x,i)=>({x:x+7,y,w:columns[i+1]-x-14,h,anchor:(x+columns[i+1])/2}))}
const cableFrames={idle:cableRow([160,318,477,634,791,947,1105,1264,1421],26,147),walkRight:cableRow([160,321,485,650,824,989,1164,1337,1500],187,151),walkLeft:cableRow([162,322,489,659,822,992,1170,1344,1508],352,155),melee:cableRow([160,302,466,618,769,933,1095,1270,1424],524,151),shoot:cableRow([161,315,463,619,774,929,1080,1236,1368,1526],693,153)};
// Frame 6 is the outgoing packet alone; use the last character pose as recovery.
cableFrames.shoot=[...cableFrames.shoot.slice(0,6),cableFrames.shoot[8],cableFrames.shoot[8]];
const cableProjectileColumns=[161,272,382,481,592,691,788,886,984,1078,1176,1265,1355,1450,1535];
function drawCableBoss(){if(!vazBossSheet.complete||!vazBossSheet.naturalWidth)return false;let name=boss.anim||'idle',frames=cableFrames[name],action=name==='melee'||name==='shoot',index=Math.floor(boss.animClock*(action?12:name==='idle'?2:8)),frame=frames[action?Math.min(index,frames.length-1):index%frames.length],ratio=boss.h/157;ctx.save();ctx.translate(boss.x+boss.w/2,boss.y+boss.h);if(!name.startsWith('walk')&&boss.face<0)ctx.scale(-1,1);if(boss.vulnerable>0){ctx.shadowColor='#308cff';ctx.shadowBlur=16}ctx.drawImage(vazBossSheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);if(name==='idle'){let capX=frame.x+65;ctx.drawImage(vazBossSheet,capX,7,65,19,(capX-frame.anchor)*ratio,-(frame.h+19)*ratio,65*ratio,19*ratio)}ctx.restore();return true}
function drawCablePacket(shot){if(!vazBossSheet.complete||!vazBossSheet.naturalWidth)return false;let index=Math.floor((shot.age||0)*20)%(cableProjectileColumns.length-1),x=cableProjectileColumns[index]+7,w=cableProjectileColumns[index+1]-cableProjectileColumns[index]-14;ctx.save();ctx.translate(shot.x+shot.w/2,shot.y+shot.h/2);if(shot.vx<0)ctx.scale(-1,1);ctx.drawImage(vazBossSheet,x,874,w,121,-29,-23,58,46);ctx.restore();return true}
function updateCableBoss(dt){let b=boss;if(b.hp<=0)return;b.t+=dt;b.animClock+=dt;b.vulnerable=Math.max(0,b.vulnerable-dt);b.cooldown=Math.max(0,b.cooldown-dt);let dx=player.x+player.w/2-(b.x+b.w/2);if(b.anim==='melee'||b.anim==='shoot'){let trigger=b.anim==='melee'?.32:.4;if(!b.fired&&b.animClock>=trigger){b.fired=true;if(b.anim==='shoot'){let count=b.hp<=50?3:1;for(let i=0;i<count;i++)shots.push({x:b.face<0?b.x-36:b.x+b.w,y:b.y+65+(i-(count-1)/2)*26,w:36,h:22,vx:b.face*340,life:4,age:0,damage:1,color:'#368dff',from:'enemy',vfxType:'cablePacket'})}else{let area={x:b.face<0?b.x-100:b.x+b.w-10,y:b.y+25,w:110,h:b.h-25};if(rect(area,player))hurtPlayer()}}if(b.animClock>=8/12){b.anim='idle';b.animClock=0;b.cooldown=.95}}else{b.face=dx<0?-1:1;if(b.cooldown===0){b.anim=Math.abs(dx)<185?'melee':'shoot';b.animClock=0;b.fired=false}else{let next=Math.abs(dx)>200?(b.face>0?'walkRight':'walkLeft'):'idle';if(next!==b.anim){b.anim=next;b.animClock=0}if(next!=='idle')b.x=clamp(b.x+b.face*55*dt,35,worldWidth-b.w-35)}}if(rect(player,b))hurtPlayer()}
const snakeSheet=new Image();snakeSheet.src='Img/vaz-enemies-spritesheet.png';
const snakeColumns=[320,470,621,774,923,1072,1220,1370,1524];
function snakeRow(y,h){return snakeColumns.slice(0,-1).map((x,i)=>({x:x+4,y,w:snakeColumns[i+1]-x-8,h,anchor:(x+snakeColumns[i+1])/2}))}
const snakeFrames={shooter:{idle:snakeRow(25,103),walkRight:snakeRow(144,92),walkLeft:snakeRow(245,96),attack:snakeRow(352,91)},defender:{idle:snakeRow(568,104),walkRight:snakeRow(685,89),walkLeft:snakeRow(783,94),attack:snakeRow(890,104)}};
const snakeProjectileColumns=[326,427,520,609,697,788,882,974,1079,1177,1274,1365,1460];
const snakeCutouts=new Map();
function snakeCutout(frame){let key=frame.x+':'+frame.y;if(snakeCutouts.has(key))return snakeCutouts.get(key);let crop=document.createElement('canvas');crop.width=frame.w;crop.height=frame.h;let c=crop.getContext('2d',{willReadFrequently:true});c.drawImage(snakeSheet,frame.x,frame.y,frame.w,frame.h,0,0,frame.w,frame.h);let pixels;try{pixels=c.getImageData(0,0,frame.w,frame.h)}catch{return null}let data=pixels.data,visited=new Uint8Array(frame.w*frame.h),queue=[];function add(x,y){if(x<0||y<0||x>=frame.w||y>=frame.h)return;let i=y*frame.w+x,o=i*4;if(visited[i])return;visited[i]=1;let max=Math.max(data[o],data[o+1],data[o+2]),min=Math.min(data[o],data[o+1],data[o+2]);if(data[o+3]===0||(min>150&&max-min<26)){queue.push(i);data[o+3]=0}}for(let x=0;x<frame.w;x++){add(x,0);add(x,frame.h-1)}for(let y=0;y<frame.h;y++){add(0,y);add(frame.w-1,y)}for(let n=0;n<queue.length;n++){let i=queue[n],x=i%frame.w,y=Math.floor(i/frame.w);add(x-1,y);add(x+1,y);add(x,y-1);add(x,y+1)}if(frame.h>50)for(let o=0;o<data.length;o+=4){let max=Math.max(data[o],data[o+1],data[o+2]),min=Math.min(data[o],data[o+1],data[o+2]);if(min>150&&max-min<26)data[o+3]=0}c.putImageData(pixels,0,0);snakeCutouts.set(key,crop);return crop}
function drawSnakeEnemy(e){if(!snakeSheet.complete||!snakeSheet.naturalWidth)return false;let name=e.anim||'idle',frames=snakeFrames[e.type===1?'shooter':'defender'][name],index=Math.floor((e.animClock||0)*(name==='idle'?1:name==='attack'?16:10)),frame=frames[name==='attack'?Math.min(7,index):index%(name==='idle'?2:8)],ratio=e.h/104;ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h);if(!name.startsWith('walk')&&(e.face||1)<0)ctx.scale(-1,1);let crop=snakeCutout(frame);if(crop)ctx.drawImage(crop,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);else ctx.drawImage(snakeSheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,-frame.h*ratio,frame.w*ratio,frame.h*ratio);ctx.restore();return true}
function drawSnakeProjectile(shot){if(!snakeSheet.complete||!snakeSheet.naturalWidth)return false;let index=Math.floor((shot.age||0)*20)%12,frame={x:snakeProjectileColumns[index],y:471,w:snakeProjectileColumns[index+1]-snakeProjectileColumns[index],h:45},crop=snakeCutout(frame);ctx.save();ctx.translate(shot.x+shot.w/2,shot.y+shot.h/2);if(shot.vx<0)ctx.scale(-1,1);if(crop)ctx.drawImage(crop,-23,-12,46,24);else ctx.drawImage(snakeSheet,frame.x,frame.y,frame.w,frame.h,-23,-12,46,24);ctx.restore();return true}
function updateSnakeEnemy(e,dt){e.t+=dt;e.animClock=(e.animClock||0)+dt;e.shot-=dt*60;e.strikeCooldown=Math.max(0,(e.strikeCooldown||0)-dt);let dx=player.x+player.w/2-(e.x+e.w/2);if(e.anim==='attack'&&e.animClock<.5){e.vx=0;if(!e.fired&&e.animClock>=.25){e.fired=true;if(e.type===1)shots.push({x:e.face<0?e.x-22:e.x+e.w,y:e.y+12,w:22,h:16,vx:e.face*275,life:4,age:0,damage:1,color:'#36b8ff',from:'enemy',vfxType:'snakeBolt'});else if(Math.abs(dx)<75&&Math.abs(player.y-e.y)<55)hurtPlayer()}}else{if(Math.abs(dx)>2)e.face=Math.sign(dx);let attack=e.type===1?e.shot<=0&&Math.abs(dx)<700:e.strikeCooldown===0&&Math.abs(dx)<65&&Math.abs(player.y-e.y)<55;if(attack){e.anim='attack';e.animClock=0;e.vx=0;e.fired=false;e.strikeCooldown=.9;if(e.type===1)e.shot=120+rnd(0,80)}else{let moving=e.type===1?Math.abs(dx)>230:Math.abs(dx)>55;e.vx=moving?(e.face||1)*(e.type===2?.95:.7):0;let next=moving?(e.face<0?'walkLeft':'walkRight'):'idle';if(e.anim!==next){e.anim=next;e.animClock=0}e.x=clamp(e.x+e.vx*70*dt,40,worldWidth-90)}}if(rect(player,e))hurtPlayer()}
const elliSheet=new Image();elliSheet.src='Img/elli-spritesheet.png';
function elliRow(columns,y,h){return columns.slice(0,-1).map((x,i)=>({x:x+5,y,w:columns[i+1]-x-10,h,anchor:(x+columns[i+1])/2}))}
const elliColumns=[135,254,371,488,604,721,837,952,1068];
const elliFrames={idle:elliRow(elliColumns,17,76),walkRight:elliRow(elliColumns,105,77),walkLeft:elliRow(elliColumns,195,78),flyRight:elliRow(elliColumns,286,73),flyLeft:elliRow(elliColumns,375,74),attack:elliRow([140,237,347,468,601,717,833,955,1096],671,90),special:elliRow([141,231,318,405,498,591,686,781,879,969,1054],870,110)};
elliFrames.attack[7].x+=12;elliFrames.attack[7].w-=12;elliFrames.special=[...elliFrames.special,...Array(6).fill(elliFrames.special[9])];
const elliProjectileFrames=elliRow([142,263,341,423,506,595,686,783,899],779,75);
const elliCutouts=new Map();
function elliCutout(frame){let key=frame.x+':'+frame.y;if(elliCutouts.has(key))return elliCutouts.get(key);let crop=document.createElement('canvas');crop.width=frame.w;crop.height=frame.h;let c=crop.getContext('2d',{willReadFrequently:true});c.drawImage(elliSheet,frame.x,frame.y,frame.w,frame.h,0,0,frame.w,frame.h);let pixels;try{pixels=c.getImageData(0,0,frame.w,frame.h)}catch{return null}let data=pixels.data,seen=new Uint8Array(frame.w*frame.h),queue=[];function add(x,y){if(x<0||y<0||x>=frame.w||y>=frame.h)return;let i=y*frame.w+x,o=i*4;if(seen[i])return;seen[i]=1;if(data[o+3]===0||(data[o]<=12&&data[o+1]<=12&&data[o+2]<=12)){data[o+3]=0;queue.push(i)}}for(let x=0;x<frame.w;x++){add(x,0);add(x,frame.h-1)}for(let y=0;y<frame.h;y++){add(0,y);add(frame.w-1,y)}for(let n=0;n<queue.length;n++){let i=queue[n],x=i%frame.w,y=Math.floor(i/frame.w);add(x-1,y);add(x+1,y);add(x,y-1);add(x,y+1)}c.putImageData(pixels,0,0);elliCutouts.set(key,crop);return crop}
elliSheet.onload=()=>{if(screen==='select'&&hero===3&&!heroLocked())renderHeroChoices()};
function drawElli(p,scale){if(!elliSheet.complete||!elliSheet.naturalWidth)return false;let name=p.anim||'idle',frames=elliFrames[name]||elliFrames.idle,action=name==='attack'||name==='special',index=Math.floor((p.animClock||0)*(name==='idle'?1:action?name==='special'?24:16:10)),frame=frames[action?Math.min(frames.length-1,index):index%(name==='idle'?2:frames.length)],flying=name.startsWith('fly'),ratio=name==='attack'?66/90:66/76;if(name==='special')ratio=66/110;ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);if((action||name==='idle')&&p.face<0)ctx.scale(-scale,scale);else ctx.scale(scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;let crop=elliCutout(frame);let dx=-frame.w*ratio/2,dy=flying?-p.h/2-frame.h*ratio/2:-frame.h*ratio;if(crop)ctx.drawImage(crop,dx,dy,frame.w*ratio,frame.h*ratio);else{ctx.globalCompositeOperation='screen';ctx.drawImage(elliSheet,frame.x,frame.y,frame.w,frame.h,dx,dy,frame.w*ratio,frame.h*ratio)}ctx.restore();return true}
function drawElliPortrait(){let canvas=menu.querySelector('.elli-selection');if(!canvas||!elliSheet.complete||!elliSheet.naturalWidth)return;canvas.width=220;canvas.height=160;let c=canvas.getContext('2d'),f=elliFrames.idle[0],crop=elliCutout(f),ratio=100/f.h,x=(220-f.w*ratio)/2;if(crop)c.drawImage(crop,x,30,f.w*ratio,100);else{canvas.style.mixBlendMode='screen';c.drawImage(elliSheet,f.x,f.y,f.w,f.h,x,30,f.w*ratio,100)}}
function elliTargets(){let targets=enemies.filter(e=>e.alive);if(boss&&boss.hp>0)targets.push(boss);return targets.sort((a,b)=>Math.hypot(a.x+a.w/2-player.x-player.w/2,a.y+a.h/2-player.y-player.h/2)-Math.hypot(b.x+b.w/2-player.x-player.w/2,b.y+b.h/2-player.y-player.h/2))}
function fireElli(special){if(player.dead||player.attack>0)return;if(special&&player.special<specialLimit())return;player.attack=special?16/24:.5;player.specialAnim=special?16/24:0;player.anim=special?'special':'attack';player.animClock=0;let targets=elliTargets();if(special){player.special=0;specialCharge=0;clearEnemyProjectiles({x:player.x-180,y:player.y-180,w:360,h:360});updateHud()}let count=special?Math.max(1,Math.min(3,targets.length)):1;for(let i=0;i<count;i++){let target=targets[i]||null,x=player.x+player.w/2,y=player.y+player.h/2,dx=target?target.x+target.w/2-x:player.face,dy=target?target.y+target.h/2-y:0,distance=Math.hypot(dx,dy)||1;shots.push({x:x-10,y:y-8,w:20,h:16,vx:dx/distance*(special?560:500),vy:dy/distance*(special?560:500),speed:special?560:500,life:3,age:0,damage:special?3:1,bossDamage:special?12:1,color:'#ff49b9',from:'player',vfxType:'elliBolt',target,empowered:special})}sound(special?720:580,special?.2:.08,'triangle')}
function steerElliShot(shot,dt){shot.age=(shot.age||0)+dt;let target=shot.target;if(target&&(target===boss?target.hp<=0:!target.alive))target=null;if(!target){target=elliTargets()[0]||null;shot.target=target}if(target){let dx=target.x+target.w/2-shot.x-shot.w/2,dy=target.y+target.h/2-shot.y-shot.h/2,distance=Math.hypot(dx,dy)||1,turn=Math.min(1,dt*12);shot.vx+=(dx/distance*shot.speed-shot.vx)*turn;shot.vy+=(dy/distance*shot.speed-shot.vy)*turn}}
function drawElliBolt(shot){if(!elliSheet.complete||!elliSheet.naturalWidth)return false;let f=elliProjectileFrames[Math.floor((shot.age||0)*20)%8],crop=elliCutout(f),width=shot.empowered?86:52,height=shot.empowered?48:30;ctx.save();ctx.translate(shot.x+shot.w/2,shot.y+shot.h/2);ctx.rotate(Math.atan2(shot.vy||0,shot.vx||1));if(crop)ctx.drawImage(crop,-width/2,-height/2,width,height);else{ctx.globalCompositeOperation='screen';ctx.drawImage(elliSheet,f.x,f.y,f.w,f.h,-width/2,-height/2,width,height)}ctx.restore();return true}
function flyElli(dt){if(player.dead){player.vx=0;player.vy=0;return}let vertical=(keys.arrowdown?1:0)-(keys.arrowup?1:0);player.vy=vertical*220;player.x=clamp(player.x+player.vx*dt,0,worldWidth-player.w);player.y=clamp(player.y+player.vy*dt,85,FLOOR_Y-player.h);player.ground=player.y>=FLOOR_Y-player.h;player.crouch=false}
function addElliEnemies(){if(hero!==3)return;enemies.forEach((e,i)=>{if(i%2===0)Object.assign(e,{airborne:true,baseY:145+(i%3)*65,y:145+(i%3)*65,h:36})});if(boss)for(let i=0;i<2;i++)enemies.push({x:350+i*360,y:155+i*80,baseY:155+i*80,w:42,h:36,hp:3,max:3,vx:0,t:i,shot:90+i*30,alive:true,type:1,airborne:true});heartPickups.forEach((pickup,i)=>{if(i>0)pickup.y=145+i*65})}
function updateAirEnemy(e,dt){e.t+=dt;e.shot-=dt*60;let dx=player.x-e.x;e.face=dx<0?-1:1;e.x=clamp(e.x+(Math.abs(dx)>180?e.face*45*dt:0),40,worldWidth-80);e.y=e.baseY+Math.sin(e.t*2)*18;if(e.shot<=0&&Math.abs(dx)<650){let sx=e.x+e.w/2,sy=e.y+e.h/2,tx=player.x+player.w/2-sx,ty=player.y+player.h/2-sy,distance=Math.hypot(tx,ty)||1;shots.push({x:sx,y:sy,w:14,h:14,vx:tx/distance*220,vy:ty/distance*220,life:4,age:0,damage:1,color:'#d775ff',from:'enemy',aimed:true});e.shot=120+rnd(0,60)}if(rect(player,e))hurtPlayer()}
function drawAirEnemy(e){ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h/2);let pulse=Math.sin(e.t*7)*4;ctx.strokeStyle='#c27eff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-16,0);ctx.lineTo(-27,-7-pulse);ctx.moveTo(16,0);ctx.lineTo(27,-7-pulse);ctx.stroke();roundRect(-21,-14,42,28,10,'#302041','#bb75ef');ctx.fillStyle='#ff6ace';ctx.fillRect(-11,-5,7,4);ctx.fillRect(4,-5,7,4);ctx.fillStyle='#be7fff';ctx.beginPath();ctx.arc(0,11,4,0,Math.PI*2);ctx.fill();ctx.restore()}
const specterSheet=new Image();specterSheet.src='Img/ritt-boss-spritesheet.png';
function specterRow(columns,y,h){return columns.slice(0,-1).map((x,i)=>({x:x+3,y,w:columns[i+1]-x-6,h,anchor:(x+columns[i+1])/2}))}
const specterFrames={idle:specterRow([0,214,430,623,811,1040,1255,1490,1740],0,246),glide:specterRow([0,211,427,634,866,1092,1330,1554,1774],248,200),shoot:specterRow([0,208,420,628,814],448,188),special:[{x:0,y:642,w:229,h:242},{x:231,y:632,w:236,h:252},{x:469,y:637,w:248,h:247},{x:719,y:634,w:274,h:250},{x:995,y:627,w:238,h:257},{x:1235,y:620,w:247,h:264},{x:1484,y:618,w:290,h:266}]};
const specterGlyphs=[{x:822,y:485,w:138,h:118},{x:960,y:485,w:138,h:118},{x:1100,y:485,w:148,h:118},{x:1250,y:485,w:158,h:118},{x:1410,y:485,w:148,h:118},{x:1560,y:485,w:210,h:118}];
function drawSpecterBoss(){if(!specterSheet.complete||!specterSheet.naturalWidth)return false;let name=boss.anim||'idle',frames=specterFrames[name],action=name==='shoot'||name==='special',index=Math.floor(boss.animClock*(name==='shoot'?7:name==='special'?6:7)),f=frames[action?Math.min(frames.length-1,index):index%frames.length],ratio=boss.h/250;ctx.save();ctx.translate(boss.x+boss.w/2,boss.y+boss.h);if((name==='glide'||name==='shoot')&&boss.face<0)ctx.scale(-1,1);if(boss.vulnerable>0){ctx.shadowColor='#7b3eff';ctx.shadowBlur=18}ctx.drawImage(specterSheet,f.x,f.y,f.w,f.h,-f.w*ratio/2,-f.h*ratio,f.w*ratio,f.h*ratio);ctx.restore();if(name==='special'&&boss.animClock<.85){ctx.save();ctx.globalAlpha=.2+.18*Math.sin(boss.animClock*18);ctx.fillStyle='#ba5cff';ctx.fillRect(boss.specialX-35,90,70,FLOOR_Y-90);ctx.strokeStyle='#d18aff';ctx.strokeRect(boss.specialX-35,90,70,FLOOR_Y-90);ctx.restore()}return true}
function drawSpecterShot(s){if(!specterSheet.complete||!specterSheet.naturalWidth)return false;ctx.save();if(s.vfxType==='specterColumn'){let f=specterFrames.special[6];ctx.drawImage(specterSheet,f.x,f.y,f.w,f.h,s.x-30,s.y,130,s.h)}else{let f=specterGlyphs[Math.floor((s.age||0)*14)%specterGlyphs.length];ctx.translate(s.x+s.w/2,s.y+s.h/2);ctx.rotate(Math.atan2(s.vy||0,s.vx||1));ctx.drawImage(specterSheet,f.x,f.y,f.w,f.h,-32,-20,64,40)}ctx.restore();return true}
function updateSpecterBoss(dt){let b=boss;if(b.hp<=0)return;b.t+=dt;b.animClock+=dt;b.cooldown=Math.max(0,b.cooldown-dt);b.vulnerable=Math.max(0,b.vulnerable-dt);b.y=FLOOR_Y-b.h-14+Math.sin(b.t*2)*10;let dx=player.x+player.w/2-(b.x+b.w/2);if(b.anim==='shoot'||b.anim==='special'){let trigger=b.anim==='special'?.85:.3;if(!b.fired&&b.animClock>=trigger){b.fired=true;if(b.anim==='special')shots.push({x:b.specialX-35,y:90,w:70,h:FLOOR_Y-90,vx:0,vy:0,life:.6,age:0,damage:1,color:'#a853ff',from:'enemy',vfxType:'specterColumn',aimed:true});else{let sx=b.x+b.w/2,sy=b.y+b.h/2,tx=player.x+player.w/2-sx,ty=player.y+player.h/2-sy,angle=Math.atan2(ty,tx),count=b.hp<=50?3:1;for(let i=0;i<count;i++){let a=angle+(i-(count-1)/2)*.15;shots.push({x:sx-12,y:sy-9,w:24,h:18,vx:Math.cos(a)*270,vy:Math.sin(a)*270,life:4,age:0,damage:1,color:'#8950ff',from:'enemy',vfxType:'specterGlyph',aimed:true})}}}if(b.animClock>=(b.anim==='special'?1.25:.62)){b.anim='idle';b.animClock=0;b.cooldown=1.1}}else{b.face=dx<0?-1:1;if(b.cooldown===0){b.cycles++;b.anim=b.cycles%3===0?'special':'shoot';b.animClock=0;b.fired=false;b.specialX=clamp(player.x+player.w/2,50,worldWidth-50)}else{let next=Math.abs(dx)>210?'glide':'idle';if(next!==b.anim){b.anim=next;b.animClock=0}if(next==='glide')b.x=clamp(b.x+b.face*45*dt,50,worldWidth-b.w-50)}}if(rect(player,b))hurtPlayer()}
const ghostSheet=new Image();ghostSheet.src='Img/ritt-enemies-spritesheet.png';
function ghostRow(columns,y,h){return columns.slice(0,-1).map((x,i)=>({x:x+12,y,w:columns[i+1]-x-24,h,anchor:(x+columns[i+1])/2}))}
const ghostColumns=[168,322,490,658,827,994,1158,1340,1530];
const ghostFrames={physical:{idle:ghostRow(ghostColumns,16,105),walkRight:ghostRow(ghostColumns,140,95),walkLeft:ghostRow(ghostColumns,253,95),attack:ghostRow([168,374,578,799,1058,1251,1406,1530],367,101)},shooter:{idle:ghostRow(ghostColumns,494,103),walkRight:ghostRow(ghostColumns,615,90),walkLeft:ghostRow(ghostColumns,721,88),attack:ghostRow([168,365,553,751,944,1149,1346,1530],824,91)}};
const ghostProjectileFrames=ghostRow([168,320,471,621,775,927,1067,1219,1364,1530],935,75);
const ghostCutouts=new Map();
function ghostCutout(frame){let key=frame.x+':'+frame.y;if(ghostCutouts.has(key))return ghostCutouts.get(key);let crop=document.createElement('canvas');crop.width=frame.w;crop.height=frame.h;let c=crop.getContext('2d',{willReadFrequently:true});c.drawImage(ghostSheet,frame.x,frame.y,frame.w,frame.h,0,0,frame.w,frame.h);let pixels;try{pixels=c.getImageData(0,0,frame.w,frame.h)}catch{return null}let data=pixels.data,seen=new Uint8Array(frame.w*frame.h),queue=[];function add(x,y){if(x<0||y<0||x>=frame.w||y>=frame.h)return;let i=y*frame.w+x,o=i*4;if(seen[i])return;seen[i]=1;if(data[o+3]===0||(data[o]<=12&&data[o+1]<=12&&data[o+2]<=12)){data[o+3]=0;queue.push(i)}}for(let x=0;x<frame.w;x++){add(x,0);add(x,frame.h-1)}for(let y=0;y<frame.h;y++){add(0,y);add(frame.w-1,y)}for(let n=0;n<queue.length;n++){let i=queue[n],x=i%frame.w,y=Math.floor(i/frame.w);add(x-1,y);add(x+1,y);add(x,y-1);add(x,y+1)}c.putImageData(pixels,0,0);ghostCutouts.set(key,crop);return crop}
function updateGhostEnemy(e,dt){e.t+=dt;e.animClock=(e.animClock||0)+dt;e.shot-=dt*60;e.strikeCooldown=Math.max(0,(e.strikeCooldown||0)-dt);let dx=player.x+player.w/2-(e.x+e.w/2);if(e.anim==='attack'&&e.animClock<.5){e.vx=0;if(!e.fired&&e.animClock>=.25){e.fired=true;if(e.type===1)shots.push({x:e.face<0?e.x-22:e.x+e.w,y:e.y+12,w:22,h:16,vx:e.face*275,life:4,age:0,damage:1,color:'#d259ff',from:'enemy',vfxType:'ghostCode'});else if(Math.abs(dx)<75&&Math.abs(player.y-e.y)<55)hurtPlayer()}}else{if(Math.abs(dx)>2)e.face=Math.sign(dx);let attack=e.type===1?e.shot<=0&&Math.abs(dx)<700:e.strikeCooldown===0&&Math.abs(dx)<65&&Math.abs(player.y-e.y)<55;if(attack){e.anim='attack';e.animClock=0;e.vx=0;e.fired=false;e.strikeCooldown=.9;if(e.type===1)e.shot=120+rnd(0,80)}else{let moving=e.type===1?Math.abs(dx)>230:Math.abs(dx)>55;e.vx=moving?(e.face||1)*(e.type===2?.95:.7):0;let next=moving?(e.face<0?'walkLeft':'walkRight'):'idle';if(e.anim!==next){e.anim=next;e.animClock=0}e.x=clamp(e.x+e.vx*70*dt,40,worldWidth-90)}}if(rect(player,e))hurtPlayer()}
function drawGhostEnemy(e){if(!ghostSheet.complete||!ghostSheet.naturalWidth)return false;let name=e.anim||'idle',frames=ghostFrames[e.type===1?'shooter':'physical'][name],index=Math.floor((e.animClock||0)*(name==='idle'?1:name==='attack'?14:10)),f=frames[name==='attack'?Math.min(frames.length-1,index):index%(name==='idle'?2:frames.length)],ratio=e.h/108;ctx.save();ctx.translate(e.x+e.w/2,e.y+e.h+Math.sin(e.t*3)*3);if(!name.startsWith('walk')&&(e.face||1)<0)ctx.scale(-1,1);let crop=ghostCutout(f);if(crop)ctx.drawImage(crop,-f.w*ratio/2,-f.h*ratio,f.w*ratio,f.h*ratio);else{ctx.globalCompositeOperation='screen';ctx.drawImage(ghostSheet,f.x,f.y,f.w,f.h,-f.w*ratio/2,-f.h*ratio,f.w*ratio,f.h*ratio)}ctx.restore();return true}
function drawGhostCode(s){if(!ghostSheet.complete||!ghostSheet.naturalWidth)return false;let f=ghostProjectileFrames[Math.floor((s.age||0)*18)%ghostProjectileFrames.length],crop=ghostCutout(f);ctx.save();ctx.translate(s.x+s.w/2,s.y+s.h/2);if(s.vx<0)ctx.scale(-1,1);if(crop)ctx.drawImage(crop,-24,-15,48,30);else{ctx.globalCompositeOperation='screen';ctx.drawImage(ghostSheet,f.x,f.y,f.w,f.h,-24,-15,48,30)}ctx.restore();return true}
const combatVfxSheet=new Image();combatVfxSheet.src='Img/combat-vfx.png';const attackVfxRows={ritt:{normalShoot:0,normalProjectile:1,normalImpact:2,specialCast:3,specialProjectile:4,specialImpact:5},vaz:{normalShoot:6,normalProjectile:7,normalImpact:8,specialCast:9,specialProjectile:10,specialImpact:11}};const attackVfxFrames={normalShoot:8,normalProjectile:12,normalImpact:8,specialCast:12,specialProjectile:16,specialImpact:12};
const animations={idle:{row:0,count:2,x:164,y:20,w:134,h:148,fps:1},walkRight:{row:1,count:8,x:164,y:174,w:134,h:143,fps:12},walkLeft:{row:2,count:8,x:164,y:322,w:134,h:150,fps:12},jumpRight:{row:3,count:6,x:164,y:478,w:150,h:138,fps:10},jumpLeft:{row:4,count:6,x:164,y:627,w:150,h:138,fps:10},attack:{row:5,count:8,x:164,y:769,w:150,h:118,fps:16},special:{row:6,count:12,x:164,y:894,w:113,h:111,fps:24}};const vazAnimations={idle:{row:0,count:2,x:176,y:0,w:110,h:160,fps:1},walkRight:{row:1,count:8,x:176,y:160,w:110,h:160,fps:12},walkLeft:{row:2,count:8,x:176,y:310,w:110,h:150,fps:12},jumpRight:{row:3,count:6,x:176,y:455,w:110,h:150,fps:10},jumpLeft:{row:4,count:6,x:176,y:595,w:110,h:150,fps:10},attack:{row:5,count:8,x:176,y:735,w:110,h:140,fps:16},special:{row:6,count:12,x:176,y:870,w:110,h:150,fps:24}};const rittAnimations={idle:{row:0,count:2,x:194,y:161,w:140,h:140,fps:1},walkRight:{row:1,count:8,x:194,y:306,w:140,h:140,fps:12},walkLeft:{row:1,count:8,x:194,y:306,w:140,h:140,fps:12},jumpRight:{row:2,count:6,x:194,y:584,w:154,h:124,fps:10},jumpLeft:{row:3,count:6,x:194,y:453,w:140,h:128,fps:10},attack:{row:5,count:8,x:194,y:714,w:140,h:122,fps:16},special:{row:6,count:12,x:194,y:842,w:111,h:130,fps:24}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a);
function sound(freq=440,d=.07,type='sine'){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch{}}
function setMenu(items,action){menu.innerHTML='';items.forEach((t,i)=>{let b=document.createElement('button');b.textContent=t;b.className=i===menuIndex?'selected':'';b.onclick=()=>{menuIndex=i;action(i)};menu.append(b)})}
function showTitle(){saveRun();paused=false;keys={};transition=0;toastTimer=0;toast.classList.add('hidden');$('#pause').classList.add('hidden');screen='title';$('.panel').classList.remove('selecting');hud.classList.add('hidden');bossHud.classList.add('hidden');overlay.classList.remove('hidden');menuIndex=0;$('.eyebrow').textContent='';$('.panel h1').innerHTML='TECH <em>TITANS</em>';$('.lead').textContent='';$('.hint').innerHTML='↑ ↓ escolher <span>•</span> ENTER confirmar';let a=i=>{if(i===0)showSelect();if(i===1)showControls()};setMenu(['JOGAR','CONTROLES'],a);renderRanking()}
function changeHero(direction){hero=(hero+direction+heroes.length)%heroes.length;menuIndex=hero;renderHeroChoices()}
function renderHeroChoices(){let h=heroes[hero],locked=heroLocked(),imageMarkup=h.secret&&!locked?'<canvas class="elli-selection hero-image" aria-label="Elli"></canvas>':h.secret?'<div class="secret-portrait'+(locked?' locked':' unlocked')+'" aria-label="'+(locked?'Personagem bloqueado':'Personagem secreto')+'">'+(locked?'?':'✦')+'</div>':'<img class="hero-image" src="Img/'+['bueno','vaz','ritt'][hero]+'-selection.png" alt="'+h.name+'" draggable="false">';menu.innerHTML=`<div class="hero-carousel" style="--hero-color:${locked?'#647082':h.color}"><button type="button" class="hero-arrow previous" aria-label="Personagem anterior">&#10094;</button><article class="hero-card${locked?' secret-locked':''}" aria-live="polite" aria-atomic="true"><span class="hero-number">0${hero+1} / 0${heroes.length}</span><div class="hero-image-wrap">${imageMarkup}</div><h2>${locked?'???':h.name}</h2><small>${locked?'BLOQUEADO':h.job}</small><p>${locked?'':h.desc}</p></article><button type="button" class="hero-arrow next" aria-label="Próximo personagem">&#10095;</button></div><div class="hero-dots" role="group" aria-label="Escolher personagem"></div>${locked?'<form class="secret-code"><label for="secretCode">CÓDIGO</label><div class="secret-code-row"><input id="secretCode" name="code" type="password" autocomplete="off" maxlength="24" aria-label="Código para liberar personagem"><button type="submit">LIBERAR</button></div><span class="secret-status" role="status" aria-live="polite"></span></form>':'<button type="button" class="hero-play">JOGAR</button>'}<button type="button" class="hero-back">VOLTAR</button>`;menu.querySelector('.previous').onclick=()=>changeHero(-1);menu.querySelector('.next').onclick=()=>changeHero(1);heroes.forEach((item,i)=>{let b=document.createElement('button');b.type='button';b.className='hero-dot'+(i===hero?' active':'');b.setAttribute('aria-label',item.secret&&!secretUnlocked?'Personagem bloqueado':item.name);b.setAttribute('aria-pressed',String(i===hero));b.onclick=()=>{hero=i;menuIndex=i;renderHeroChoices()};menu.querySelector('.hero-dots').append(b)});if(locked)menu.querySelector('.secret-code').onsubmit=e=>{e.preventDefault();unlockSecret(menu.querySelector('#secretCode').value)};else menu.querySelector('.hero-play').onclick=showNickname;menu.querySelector('.hero-back').onclick=showTitle;if(hero===3&&!locked)drawElliPortrait()}
function showSelect(){screen='select';$('#ranking').classList.add('hidden');keys={};menuIndex=hero;overlay.classList.remove('hidden');$('.panel').classList.add('selecting');$('.eyebrow').textContent='';$('.panel h1').innerHTML='PERSONAGENS';$('.lead').textContent='';$('.hint').innerHTML='← → TROCAR <span>•</span> ENTER JOGAR <span>•</span> ESC VOLTAR';renderHeroChoices()}function showControls(){screen='controls';$('#ranking').classList.add('hidden');$('.panel').classList.remove('selecting');$('.eyebrow').textContent='';$('.panel h1').innerHTML='CONTROLES';$('.lead').innerHTML='← → mover &nbsp; · &nbsp; ↑ pular &nbsp; · &nbsp; ↓ agachar<br><br><b>Z</b> ataque &nbsp; · &nbsp; <b>X</b> especial &nbsp; · &nbsp; <b>ESC</b> pausa<br><br>Acertos carregam o especial.<br>Elli: ↑ subir · ↓ descer.';$('.hint').innerHTML='ENTER para voltar';menu.innerHTML='';let b=document.createElement('button');b.textContent='VOLTAR';b.onclick=showTitle;menu.append(b)}
function startGame(){if(!nickname){showNickname();return}score=0;levelStartScore=0;awardedLevels.clear();runActive=true;$('#scoreValue').textContent=score;if(heroLocked()){menu.querySelector('#secretCode').focus({preventScroll:true});return}keys={};paused=false;transition=0;$('#pause').classList.add('hidden');level=0;specialCharge=0;hero=clamp(hero,0,heroes.length-1);newLevel(true);screen='game';overlay.classList.add('hidden');hud.classList.remove('hidden')}
function newLevel(resetHealth=false){if(resetHealth&&screen==='game'){score=levelStartScore;awardedLevels.delete(level);$('#scoreValue').textContent=score}else levelStartScore=score;let bossLevel=level%4===3,preservedHp=!resetHealth&&!bossLevel&&player?player.hp:null,maxHearts=hero===0?5:hero===1?6:hero===2?7:5,chapter=Math.floor(level/4),difficulty=1+Math.floor(level/4)+(level%4===2?1:0);worldWidth=bossLevel?1100:2100+level%4*130;player={x:70,y:FLOOR_Y-64,vx:0,vy:0,w:34,h:58,hp:preservedHp===null?maxHearts:preservedHp,max:maxHearts,face:1,ground:false,crouch:false,attack:0,special:specialCharge,invuln:0,dead:0,walk:0,anim:'idle',animClock:0,specialAnim:0,dropTimer:0};camera=0;shots=[];particles=[];attackVfx=[];heartPickups=(bossLevel?[260,570]:[500,1050,1700]).map(x=>({x,y:FLOOR_Y-30}));enemies=[];boss=null;
platforms=[{x:0,y:FLOOR_Y,w:worldWidth,h:56},{x:260,y:352,w:150,h:18},{x:520,y:287,w:140,h:18},{x:800,y:367,w:160,h:18},{x:1120,y:302,w:170,h:18},{x:1470,y:357,w:140,h:18},{x:1770,y:282,w:150,h:18}];if(bossLevel){platforms=[{x:0,y:FLOOR_Y,w:worldWidth,h:56},{x:170,y:335,w:130,h:18},{x:420,y:272,w:150,h:18},{x:700,y:335,w:130,h:18},{x:900,y:272,w:120,h:18}];boss={x:770,y:FLOOR_Y-104,w:116,h:104,hp:hero===0?80:hero===2?75:100,max:hero===0?80:hero===2?75:100,t:0,vulnerable:0,attack:100};if(hero===0)Object.assign(boss,{kind:'printer',w:140,h:128,y:FLOOR_Y-128,face:-1,anim:'idle',animClock:0,cooldown:1.2,fired:false});if(hero===1)Object.assign(boss,{kind:'cable',w:128,h:148,y:FLOOR_Y-148,face:-1,anim:'idle',animClock:0,cooldown:1.2,fired:false});if(hero===2)Object.assign(boss,{kind:'specter',w:144,h:148,y:FLOOR_Y-162,face:-1,anim:'idle',animClock:0,cooldown:1.2,fired:false,cycles:0,specialX:500});bossHud.classList.remove('hidden');$('#bossName').textContent=heroes[hero].boss;$('#bossMeter').style.width='100%';$('#bossHp').textContent=`${boss.hp} / ${boss.max}`;say(`${heroes[hero].boss}`,1700)}else{bossHud.classList.add('hidden');let count=3+difficulty*2;for(let i=0;i<count;i++)enemies.push({x:390+i*(worldWidth-650)/count,y:FLOOR_Y-46,w:42,h:46,hp:2+Math.floor(difficulty/2),max:2+Math.floor(difficulty/2),vx:rnd(-.65,.65),t:rnd(0,4),type:i%3,shot:100+rnd(0,120),alive:true})}addElliEnemies();$('#movementHint').textContent=hero===3?'← → MOVER · ↑ SUBIR · ↓ DESCER':'← → MOVER · ↑ PULAR · ↓ AGACHAR';$('#heroName').textContent=heroes[hero].name;$('#portrait').textContent=heroes[hero].name[0];$('#levelLabel').textContent=`FASE ${chapter+1}-${level%4+1} · ${heroes[hero].world}`;updateHud();}
function say(t,ms=1400){toast.innerHTML=t;toast.classList.remove('hidden');toastTimer=ms/1000}
function specialLimit(){return hero===2?5:7}
function clearEnemyProjectiles(area){shots.forEach(s=>{if(s.from==='enemy'&&(!area||rect(area,s)))s.life=0})}

const itemSheet=new Image();itemSheet.src='Img/cyberpunk-items-v1.png';
const itemRects={heart:[238,204,352,304],coffee:[980,94,346,450],platform:[38,664,1460,272]};
let heartIconUrl='';
itemSheet.onload=()=>{let c=document.createElement('canvas');c.width=44;c.height=38;let g=c.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(itemSheet,...itemRects.heart,0,0,44,38);heartIconUrl=c.toDataURL();if(player)updateHud()};
function drawItem(name,x,y,w,h){if(!itemSheet.complete||!itemSheet.naturalWidth)return false;ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(itemSheet,...itemRects[name],x,y,w,h);ctx.restore();return true}
function drawLifeIcons(){let el=$('#hearts');el.setAttribute('aria-label',player.hp+' de '+player.max+' corações');if(!heartIconUrl){el.textContent='♥ '.repeat(Math.max(0,player.hp))+'♡ '.repeat(Math.max(0,player.max-player.hp));return}el.innerHTML=Array.from({length:player.max},(_,i)=>'<img src="'+heartIconUrl+'" alt="" width="18" height="16" style="display:inline-block;vertical-align:middle;image-rendering:pixelated;margin-right:2px;'+(i>=player.hp?'filter:brightness(0);':'')+'">').join('')}

function updateHud(){drawLifeIcons();$('#specialText').textContent=player.special>=specialLimit()?'PRONTO!':`${player.special}/${specialLimit()} HITS`;$('#specialMeter').style.width=`${Math.min(player.special,specialLimit())/specialLimit()*100}%`;$('#specialText').style.color=player.special>=specialLimit()?'#70f3d0':''}
function hurtPlayer(){if(player.invuln>0||player.dead)return;player.hp--;player.invuln=1.25;player.vy=-260;player.vx=-player.face*180;sound(150,.16,'sawtooth');updateHud();if(player.hp<=0){player.dead=1;showGameOver()}}
function hitEnemy(e,damage=1){if(player.dead||!e.alive)return;e.hp-=damage;if(hero===0)burst(e.x+e.w/2,e.y+e.h/2,heroes[hero].color,8);if(damage===1){player.special=Math.min(specialLimit(),player.special+1);specialCharge=player.special;if(player.special===specialLimit())say('ESPECIAL PRONTO',850)}if(e.hp<=0){e.alive=false;addScore(10);sound(210,.1,'triangle')}updateHud()}
function hitBoss(damage,chargeSpecial=false){if(player.dead)return;if(!boss||boss.hp<=0)return;boss.hp=Math.max(0,boss.hp-damage);if(chargeSpecial){player.special=Math.min(specialLimit(),player.special+1);specialCharge=player.special;if(player.special===specialLimit())say('ESPECIAL PRONTO',850);updateHud()}boss.vulnerable=.24;$('#bossMeter').style.width=`${boss.hp/boss.max*100}%`;$('#bossHp').textContent=`${boss.hp} / ${boss.max}`;if(hero===0)burst(boss.x+boss.w/2,boss.y+boss.h/2,heroes[hero].color,15);sound(180,.1,'square');if(boss.hp===0){if(!awardedLevels.has(level)){addScore(500);awardedLevels.add(level)}say('CHEFE DERROTADO',3500);transition=3}}
function attackDirection(){if(keys.arrowup)return{x:0,y:-1};if(keys.arrowdown)return{x:0,y:1};if(keys.arrowleft)return{x:-1,y:0};if(keys.arrowright)return{x:1,y:0};if(Math.abs(player.vx||0)>35)return{x:Math.sign(player.vx),y:0};return{x:player.face||1,y:0}}function queueAreaAttackVfx(special,targets,heroIndex=hero){let direction=attackDirection(),face=direction.x||player.face||1,offset=heroIndex===2?34:24,originX=player.x+player.w/2+direction.x*offset,originY=direction.y<0?player.y-offset:direction.y>0?player.y+player.h+offset:player.y+26;attackVfx.push({hero:heroIndex,special,phase:'cast',t:0,originX,originY,x:originX,y:originY,face,direction,followPlayer:true,socketOffset:offset,range:heroIndex===2?(special?worldWidth:600):(special?330:150),targets:targets.map(p=>({...p}))})}
function queueVazShotVfx(shot){let direction=shot.direction,face=direction.x||player.face||1,offset=24,originX=direction.x?player.x+player.w/2+direction.x*offset:player.x+player.w/2,originY=direction.y<0?player.y-offset:direction.y>0?player.y+player.h+offset:player.y+24;attackVfx.push({hero:1,special:false,phase:'cast',t:0,originX,originY,x:originX,y:originY,face,direction,followPlayer:true,socketOffset:offset,shot})}
function updateAttackVfx(dt){let next=[];for(const v of attackVfx){v.t+=dt;if(v.phase==='cast'){if(v.followPlayer){let direction=v.direction||{x:v.face||1,y:0};v.originX=direction.x?player.x+player.w/2+direction.x*v.socketOffset:player.x+player.w/2;v.originY=direction.y<0?player.y-v.socketOffset:direction.y>0?player.y+player.h+v.socketOffset:player.y+(v.shot?24:26);v.x=v.originX;v.y=v.originY;if(v.shot){let d=v.shot.direction,s=v.shot;s.x=d.x>0?player.x+player.w:d.x<0?player.x-s.w:player.x+player.w/2-s.w/2;s.y=d.y<0?player.y-s.h:d.y>0?player.y+player.h:player.y+24}}let castDuration=(v.special?12:8)/24;if(v.t<castDuration){next.push(v);continue}if(v.shot){if(v.shot.visualHits.length){for(const hit of v.shot.visualHits){let target={x:hit.x,y:hit.y};next.push({...v,shot:null,phase:'projectile',t:0,x:v.originX,y:v.originY,target,face:Math.sign(target.x-v.originX)||v.face})}}else if(v.shot.life>0){shots.push(v.shot);next.push({...v,phase:'projectile',t:0})}continue}let targets=v.targets.length?v.targets:[{x:v.originX+v.face*v.range,y:v.originY,miss:true}];for(const target of targets)next.push({...v,phase:'projectile',t:0,x:v.originX,y:v.originY,target,face:Math.sign(target.x-v.originX)||v.face});continue}if(v.phase==='projectile'){if(v.shot){if(v.shot.visualHits.length){for(const hit of v.shot.visualHits)next.push({...v,phase:'impact',t:0,x:hit.x,y:hit.y})}else if(v.shot.life>0){v.x=v.shot.x+v.shot.w/2;v.y=v.shot.y+v.shot.h/2;next.push(v)}continue}if((v.hero===1||v.hero===2)&&v.target.entity){let entity=v.target.entity;if(v.target.boss?entity.hp<=0:!entity.alive)continue;v.target.x=entity.x+entity.w/2;v.target.y=entity.y+entity.h/2}let dx=v.target.x-v.originX,dy=v.target.y-v.originY,distance=Math.hypot(dx,dy);if(distance>0)v.direction={x:dx/distance,y:dy/distance};let flight=Math.max(.06,distance/620),progress=Math.min(1,v.t/flight);v.x=v.originX+dx*progress;v.y=v.originY+dy*progress;if(progress>=1){if((v.hero===1||v.hero===2)&&v.target.entity){if(v.target.boss)hitBoss(v.target.damage,v.target.charge);else hitEnemy(v.target.entity,v.target.damage)}if(!v.target.miss)next.push({...v,phase:'impact',t:0,x:v.target.x,y:v.target.y});continue}next.push(v);continue}let frames=v.special?12:8;if(v.t<frames/24)next.push(v)}attackVfx=next}
function attack(special=false){if(hero===3){fireElli(special);return;}if(special){if(player.special<specialLimit())return;player.special=0;specialCharge=0;player.attack=.5;player.specialAnim=.5;player.anim='special';player.animClock=0;let col=heroes[hero].color;if(hero===0)burst(player.x+player.w/2,player.y+player.h/2,col,34);sound(180,.34,'sawtooth');let specialArea={x:player.x-310,y:player.y-120,w:620,h:280};if(hero===0||hero===1)clearEnemyProjectiles(specialArea);let specialDamage=hero===0?20:hero===1?20:3;let attackTargets=[];if(hero===1){for(const e of enemies){if(e.alive&&Math.abs(e.x-player.x)<330)attackTargets.push({x:e.x+e.w/2,y:e.y+e.h/2,entity:e,damage:20})}if(boss&&boss.hp>0&&Math.abs(boss.x-player.x)<490)attackTargets.push({x:boss.x+boss.w/2,y:boss.y+boss.h/2,entity:boss,boss:true,damage:20,charge:false});queueAreaAttackVfx(true,attackTargets,hero);updateHud();return}if(hero===2){for(const e of enemies){if(e.alive)attackTargets.push({x:e.x+e.w/2,y:e.y+e.h/2,entity:e,damage:3})}if(boss&&boss.hp>0)attackTargets.push({x:boss.x+boss.w/2,y:boss.y+boss.h/2,entity:boss,boss:true,damage:10,charge:false});queueAreaAttackVfx(true,attackTargets,hero);updateHud();return}if(boss){if(Math.abs(boss.x-player.x)<490){if(hero===1||hero===2)attackTargets.push({x:boss.x+boss.w/2,y:boss.y+boss.h/2,...(hero===2?{entity:boss,boss:true,damage:10,charge:false}:{})});if(hero!==2)hitBoss(specialDamage)}}else enemies.forEach(e=>{if(e.alive&&Math.abs(e.x-player.x)<330){if(hero===1||hero===2)attackTargets.push({x:e.x+e.w/2,y:e.y+e.h/2,...(hero===2?{entity:e,damage:specialDamage}:{})});if(hero!==2)hitEnemy(e,specialDamage)}});if(hero===1||hero===2)queueAreaAttackVfx(true,attackTargets,hero);else shots.push({...specialArea,t:.4,special:true,color:col});updateHud();return}
if(player.attack>0)return;player.attack=.5;player.anim='attack';player.animClock=0;sound(hero===1?620:hero===2?400:300,.06);if(hero===1){let direction=attackDirection(),vertical=direction.y!==0,w=vertical?13:24,h=vertical?24:13,x=direction.x>0?player.x+player.w:direction.x<0?player.x-w:player.x+player.w/2-w/2,y=direction.y<0?player.y-h:direction.y>0?player.y+player.h:player.y+24;let shot={x,y,w,h,vx:direction.x*590,vy:direction.y*590,direction,life:1.15,damage:1,color:heroes[hero].color,from:'player',vfxType:'vazNormal',visualHits:[]};queueVazShotVfx(shot);return}let reach=hero===0?115:hero===2?600:75;let box={x:player.face>0?player.x+player.w:player.x-reach,y:player.y+(player.crouch?32:8),w:reach,h:player.crouch?24:player.h-14};if(hero===0)clearEnemyProjectiles(box);let attackTargets=[];if(boss&&rect(box,boss)){if(hero===2)attackTargets.push({x:boss.x+boss.w/2,y:boss.y+boss.h/2,entity:boss,boss:true,damage:1,charge:true});else hitBoss(1,true)}enemies.forEach(e=>{if(e.alive&&rect(box,e)){if(hero===2)attackTargets.push({x:e.x+e.w/2,y:e.y+e.h/2,entity:e,damage:1});else hitEnemy(e)}});if(hero===2)queueAreaAttackVfx(false,attackTargets,hero);else if(hero!==0)shots.push({x:box.x,y:box.y+box.h/2-5,w:box.w,h:10,life:.13,t:.13,special:false,color:heroes[hero].color})}
const rect=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function burst(x,y,color,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:rnd(-220,220),vy:rnd(-230,120),life:rnd(.25,.65),max:.65,color,size:rnd(2,5)})}
const pauseButtons=Array.from(document.querySelectorAll('#pauseMenu button'));
function selectPauseItem(index){pauseIndex=index;pauseButtons.forEach((button,i)=>button.classList.toggle('selected',i===pauseIndex))}
function openPause(){paused=true;keys={};selectPauseItem(0);$('#pause').classList.remove('hidden');pauseButtons[0].focus({preventScroll:true})}
function resumeGame(){paused=false;keys={};$('#pause').classList.add('hidden');canvas.focus({preventScroll:true})}
function activatePauseItem(index){if(index===0){resumeGame();return}if(index===1){transition=0;specialCharge=0;toastTimer=0;toast.classList.add('hidden');newLevel(true);resumeGame();return}showTitle()}
pauseButtons.forEach((button,i)=>{button.onclick=()=>activatePauseItem(i);button.onfocus=()=>selectPauseItem(i)});
function keydown(e){let k=e.key.toLowerCase();if(screen==='nickname'){if(k==='escape'){e.preventDefault();showSelect()}return}if(screen==='gameover'){if(k==='enter'&&!e.repeat){e.preventDefault();showTitle()}return}if(screen==='select'&&e.target&&e.target.tagName==='INPUT'){if(k==='enter'){e.preventDefault();unlockSecret(e.target.value)}else if(k==='escape'){e.preventDefault();e.target.blur()}return;}if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))e.preventDefault();if(screen==='game'){if(k==='escape'){e.preventDefault();if(!e.repeat){if(paused)resumeGame();else openPause()}return}if(paused){if(k==='arrowup'||k==='arrowdown'){e.preventDefault();selectPauseItem((pauseIndex+(k==='arrowdown'?1:pauseButtons.length-1))%pauseButtons.length);pauseButtons[pauseIndex].focus({preventScroll:true})}else if(k==='enter'||k===' '){e.preventDefault();if(!e.repeat)activatePauseItem(pauseIndex)}return;}if(player.dead){if(k==='enter'){specialCharge=0;newLevel(true)}return}if(k==='arrowdown'&&player.ground&&player.y+player.h<FLOOR_Y){player.dropTimer=.24;player.ground=false;player.vy=80}if(k==='z'&&!(hero>=1&&e.repeat))attack(false);if(k==='x')attack(true)}else if(screen==='select'&&k==='escape'){showTitle();return}else if(k==='enter'||k===' '){if(screen==='title'){if(menuIndex===0)showSelect();else showControls()}else if(screen==='select'){hero=menuIndex;showNickname()}else if(screen==='controls')showTitle()}else if(screen==='title'&&(k==='arrowdown'||k==='arrowup')){menuIndex=(menuIndex+1)%2;setMenu(['JOGAR','CONTROLES'],i=>{if(i===0)showSelect();if(i===1)showControls()})}else if(screen==='select'&&(k==='arrowleft'||k==='arrowright')){changeHero(k==='arrowright'?1:-1);return}keys[k]=true}function keyup(e){keys[e.key.toLowerCase()]=false}window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',()=>keys={});
function update(dt){if(screen!=='game'||paused||player.dead)return;if(transition>0){transition-=dt;if(transition<=0){if(level<11){level++;newLevel()}else{showTitle();say('TECH TITANS<br><small>VITÓRIA!</small>',4000)}}return}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)toast.classList.add('hidden')}player.attack=Math.max(0,player.attack-dt);player.specialAnim=Math.max(0,player.specialAnim-dt);player.invuln=Math.max(0,player.invuln-dt);player.dropTimer=Math.max(0,(player.dropTimer||0)-dt);player.crouch=hero===3?false:keys.arrowdown;let dir=(keys.arrowright?1:0)-(keys.arrowleft?1:0),speed=player.crouch?100:260;if(dir){player.face=dir;player.vx+=((dir*speed)-player.vx)*Math.min(1,dt*13)}else player.vx*=Math.pow(.0008,dt);player.vx=clamp(player.vx,-speed,speed);if(hero===3){flyElli(dt)}else{if(keys.arrowup&&player.ground){player.vy=-590;player.ground=false;sound(520,.1)}player.vy=Math.min(880,player.vy+1500*dt);player.x=clamp(player.x+player.vx*dt,0,worldWidth-player.w);let py=player.y;player.y+=player.vy*dt;player.ground=false;if(player.vy>=0&&player.dropTimer<=0)for(let p of platforms){if(py+player.h<=p.y+4&&player.y+player.h>=p.y&&player.x+player.w>p.x&&player.x<p.x+p.w){player.y=p.y-player.h;player.vy=0;player.ground=true;break}}player.y=Math.min(player.y,H+100);if(player.y>H)hurtPlayer()}for(let i=heartPickups.length-1;i>=0;i--){let pickup=heartPickups[i];if(player.hp<player.max&&rect(player,{x:pickup.x-11,y:pickup.y-11,w:22,h:22})){player.hp=Math.min(player.max,player.hp+1);heartPickups.splice(i,1);say('VIDA RECUPERADA',700);updateHud()}}
let previousAnimation=player.anim;if(player.specialAnim>0){player.anim='special'}else if(player.attack>0){player.anim='attack'}else if(!player.ground){player.anim=hero===3?(player.face>0?'flyRight':'flyLeft'):(player.face>0?'jumpRight':'jumpLeft')}else if(Math.abs(player.vx)>35){player.anim=player.face>0?'walkRight':'walkLeft'}else{if(player.anim!=='idle')player.animClock=0;player.anim='idle'}if(hero>=1&&player.anim!==previousAnimation&&!(player.anim.startsWith('jump')&&previousAnimation.startsWith('jump')))player.animClock=0;player.animClock+=dt;
if(!boss&&!player.dead&&player.x>worldWidth-85&&(player.ground||hero===3)){if(!awardedLevels.has(level)){addScore([30,50,75][level%4]);awardedLevels.add(level)}transition=.65;say(level===11?'':`FASE CONCLUÍDA`,850);sound(740,.2)}
for(let e of enemies){if(!e.alive)continue;if(hero===3&&e.airborne){updateAirEnemy(e,dt);continue}if(hero===1){updateSnakeEnemy(e,dt);continue}if(hero===2){updateGhostEnemy(e,dt);continue}e.t+=dt;e.shot-=dt*60;let dx=player.x-e.x;if(hero===0&&e.type!==1)movePhysicalPrinter(e);else if(e.type===2&&Math.abs(dx)<390)e.vx=Math.sign(dx)*(.75+level*.08);else if(Math.random()<.01)e.vx=-e.vx;e.x=clamp(e.x+e.vx*70*dt,40,worldWidth-90);if(hero===0)updateSmallPrinterAnimation(e,dt);if(e.shot<=0&&e.type===1){let direction=Math.sign(dx)||1;if(hero===0){e.anim='attack';e.animClock=0;e.face=direction}shots.push({x:hero===0?(direction<0?e.x-20:e.x+e.w):e.x,y:e.y+14,w:20,h:15,vx:direction*260,life:4,age:0,damage:1,color:'#f2d283',from:'enemy',label:heroes[hero].shot,...(hero===0?{vfxType:'printerPaper',paperSize:28}:{})});e.shot=120+rnd(0,80)}if(Math.abs(player.x-e.x)<40&&Math.abs(player.y-e.y)<42)hurtPlayer()}
if(boss&&boss.kind==='printer')updatePrinterBoss(dt);else if(boss&&boss.kind==='cable')updateCableBoss(dt);else if(boss&&boss.kind==='specter')updateSpecterBoss(dt);else if(boss){boss.t+=dt;boss.attack-=dt*60;boss.vulnerable=Math.max(0,boss.vulnerable-dt);boss.x=clamp(boss.x+Math.sin(boss.t*.72)*55*dt+(player.x>boss.x?1:-1)*12*dt,610,930);if(boss.attack<=0){boss.attack=85+Math.random()*65;let type=Math.random();if(type<.58){let n=type<.25?3:1;for(let i=0;i<n;i++)shots.push({x:boss.x,y:boss.y+45+i*18,w:28,h:18,vx:-260-rnd(0,70),life:5,damage:1,color:heroes[hero].color,label:heroes[hero].shot,from:'enemy'})}else if(Math.abs(player.x-boss.x)<150)hurtPlayer()}if(rect(player,boss)&&Math.abs(player.x-boss.x)<65)hurtPlayer()}
for(let s of shots){if(s.life<=0)continue;s.life-=dt;if(s.special)s.t-=dt;if(s.from==='player'){if(s.vfxType==='elliBolt')steerElliShot(s,dt);s.x+=(s.vx||0)*dt;s.y+=(s.vy||0)*dt;if(boss&&rect(s,boss)){hitBoss(s.bossDamage||s.damage,!s.empowered);if(s.vfxType==='vazNormal')s.visualHits.push({x:boss.x+boss.w/2,y:boss.y+boss.h/2});s.life=0}else enemies.forEach(e=>{if(e.alive&&rect(s,e)){hitEnemy(e,s.damage);if(s.vfxType==='vazNormal')s.visualHits.push({x:e.x+e.w/2,y:e.y+e.h/2});s.life=0}})}else if(s.from==='enemy'){if(hero===3&&!s.aimed){let dx=player.x+player.w/2-s.x,dy=player.y+player.h/2-s.y,distance=Math.hypot(dx,dy)||1,speed=Math.abs(s.vx)||220;s.vx=dx/distance*speed;s.vy=dy/distance*speed;s.aimed=true}s.age=(s.age||0)+dt;s.x+=s.vx*dt;s.y+=(s.vy||0)*dt;if(rect(s,player)) {hurtPlayer();s.life=0}}}shots=shots.filter(s=>s.life>0&&s.x>-200&&s.x<worldWidth+200);
updateAttackVfx(dt);for(let p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt}particles=particles.filter(p=>p.life>0);camera+=(clamp(player.x-W*.38,0,worldWidth-W)-camera)*Math.min(1,dt*5);updateHud()}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}}
function drawAttackVfx(){for(const v of attackVfx){let sheet=attackVfxRows[v.hero===1?'vaz':'ritt'],key=v.phase==='cast'?(v.special?'specialCast':'normalShoot'):v.phase==='projectile'?(v.special?'specialProjectile':'normalProjectile'):(v.special?'specialImpact':'normalImpact'),count=attackVfxFrames[key],row=sheet[key],frame=v.phase==='projectile'?Math.floor(v.t*24)%count:Math.min(count-1,Math.floor(v.t*24));if(!combatVfxSheet.complete||combatVfxSheet.naturalWidth<(frame+1)*128||combatVfxSheet.naturalHeight<(row+1)*128)continue;let width=v.phase==='cast'?40:v.phase==='projectile'?(v.shot?90:(v.special?96:78)):(v.special?100:82),height=v.phase==='cast'?40:v.phase==='projectile'?(v.shot?30:(v.special?60:42)):width;ctx.save();ctx.imageSmoothingEnabled=false;ctx.translate(v.x,v.y);if(v.direction){if(Math.abs(v.direction.y)>.001)ctx.rotate(Math.atan2(v.direction.y,v.direction.x));else if(v.direction.x<0)ctx.scale(-1,1)}else if(v.face<0)ctx.scale(-1,1);ctx.drawImage(combatVfxSheet,frame*128,row*128,128,128,v.phase==='projectile'&&v.shot?-width+Math.max(v.shot.w,v.shot.h)/2:-width/2,-height/2,width,height);ctx.restore()}}
function draw(){ctx.clearRect(0,0,W,H);let h=heroes[hero]||heroes[0],ch=screen==='game'?Math.floor(level/4):hero;let bg=['#101922','#0c1b25','#101b20'][Math.min(ch,2)],accent=hero===3?heroes[3].color:['#f17062','#45cfc5','#91df69'][Math.min(ch,2)];if(backgroundImage.complete&&backgroundImage.naturalWidth)ctx.drawImage(backgroundImage,0,0,W,H);else{let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,bg);g.addColorStop(1,'#101927');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}if(screen==='game'){ctx.save();ctx.translate(-camera,0);for(let p of platforms){if(p.y===FLOOR_Y)continue;if(drawItem('platform',p.x,p.y,p.w,Math.max(28,p.w*272/1460)))continue;ctx.fillStyle='#172938';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=accent;ctx.globalAlpha=.8;ctx.fillRect(p.x,p.y,p.w,4);ctx.globalAlpha=1;ctx.strokeStyle='#34495b';ctx.strokeRect(p.x,p.y,p.w,p.h);if(p.y===FLOOR_Y){for(let x=p.x;x<p.x+p.w;x+=42){ctx.strokeStyle='#203444';ctx.beginPath();ctx.moveTo(x,p.y+10);ctx.lineTo(x+25,p.y+40);ctx.stroke()}}}
// exit portal
if(!boss){let x=worldWidth-80;ctx.shadowBlur=22;ctx.shadowColor=accent;roundRect(x,FLOOR_Y-84,46,84,18,'#16323a',accent);ctx.shadowBlur=0;ctx.fillStyle=accent;ctx.font='bold 12px monospace';ctx.fillText('EXIT',x+8,FLOOR_Y-36);ctx.beginPath();ctx.arc(x+23,FLOOR_Y-64,13,0,Math.PI*2);ctx.strokeStyle='#eafffd';ctx.stroke()}
for(let e of enemies){if(!e.alive)continue;drawEnemy(e,h,accent)}if(boss)drawBoss(h,accent);for(let life of heartPickups){if(drawItem('coffee',life.x-14,life.y-24,28,36))continue;ctx.save();ctx.fillStyle='#ff5e83';ctx.shadowColor='#ff3d70';ctx.shadowBlur=16;ctx.font='bold 27px monospace';ctx.textAlign='center';ctx.fillText('☕',life.x,life.y+9);ctx.restore()}
for(let s of shots){if(s.vfxType==='vazNormal')continue;if(s.vfxType==='printerPaper'&&drawPrinterPaper(s))continue;if(s.vfxType==='cablePacket'&&drawCablePacket(s))continue;if(s.vfxType==='snakeBolt'&&drawSnakeProjectile(s))continue;if(s.vfxType==='elliBolt'&&drawElliBolt(s))continue;if(s.vfxType==='ghostCode'&&drawGhostCode(s))continue;if((s.vfxType==='specterGlyph'||s.vfxType==='specterColumn')&&drawSpecterShot(s))continue;if(s.special){ctx.save();ctx.globalAlpha=clamp(s.t/.4,0,1)*.7;ctx.strokeStyle=s.color;ctx.lineWidth=13;ctx.shadowBlur=20;ctx.shadowColor=s.color;ctx.beginPath();ctx.ellipse(s.x+s.w/2,s.y+s.h/2,s.w/2,s.h/2,0,0,Math.PI*2);ctx.stroke();ctx.restore()}else{ctx.shadowBlur=13;ctx.shadowColor=s.color;roundRect(s.x,s.y,s.w,s.h,5,s.color);ctx.shadowBlur=0;if(s.label){ctx.fillStyle='#12212b';ctx.font='bold 11px monospace';ctx.fillText(s.label,s.x+2,s.y+12)}}}
drawAttackVfx();for(let p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;drawPlayer(player,h);ctx.restore();if(transition>0){ctx.fillStyle=`rgba(4,10,16,${clamp(1-transition,0,.88)})`;ctx.fillRect(0,0,W,H)}}else if(screen==='title'||screen==='select'||screen==='controls'){// idle hero showcase behind overlay
drawPlayer({x:680,y:FLOOR_Y-75,w:45,h:75,face:-1,ground:true,attack:0,invuln:0,crouch:false,walk:0},heroes[hero],0,1.25)}requestAnimationFrame(frame)}
const vazActionFrames={
jumpRight:[{x:205,y:475,w:95,h:116,anchor:250},{x:345,y:468,w:105,h:112,anchor:391},{x:490,y:461,w:110,h:114,anchor:543},{x:630,y:458,w:112,h:113,anchor:687},{x:775,y:466,w:108,h:113,anchor:831},{x:915,y:474,w:107,h:117,anchor:971}],
jumpLeft:[{x:200,y:605,w:99,h:112,anchor:249},{x:351,y:599,w:114,h:117,anchor:409},{x:487,y:599,w:112,h:118,anchor:545},{x:630,y:600,w:111,h:119,anchor:687},{x:774,y:610,w:111,h:111,anchor:832},{x:915,y:610,w:102,h:108,anchor:967}],
attack:[{x:215,y:728,w:121,h:114,anchor:258},{x:355,y:728,w:134,h:114,anchor:399},{x:495,y:728,w:136,h:114,anchor:541},{x:631,y:728,w:124,h:114,anchor:680,trimLeft:20},{x:760,y:728,w:137,h:114,anchor:795},{x:900,y:728,w:142,h:114,anchor:936},{x:1042,y:728,w:146,h:114,anchor:1080,trimLeft:12},{x:1185,y:728,w:155,h:114,anchor:1226,trimLeft:14}]
};

function vazPoseRow(xs,y,h,feet){return xs.map(([x,w,anchor])=>({x,y,w,h,anchor,feet}))}
vazActionFrames.idle=vazPoseRow(Array.from({length:8},(_,i)=>[176+i*112,88,216+i*112]),18,140,157);
vazActionFrames.walkRight=vazPoseRow(Array.from({length:8},(_,i)=>[176+i*111,94,218+i*111]),178,132,309);
vazActionFrames.walkLeft=vazPoseRow(Array.from({length:8},(_,i)=>[187+i*111,94,229+i*111]),322,130,451);
vazActionFrames.special=vazPoseRow([[194,70,224],[270,78,306],[354,90,393],[354,90,393],[354,90,393],[354,90,393],[354,90,393],[354,90,393],[1358,82,1400],[1439,80,1479],[1439,80,1479],[1439,80,1479]],868,118,983);

function drawVazAction(p,scale){let frames=vazActionFrames[p.anim];if(!frames||!vazSpriteSheet.complete||!vazSpriteSheet.naturalWidth)return false;let loop=p.anim==='idle'||p.anim.startsWith('walk'),index=Math.floor((p.animClock||0)*(p.anim==='idle'?1:p.anim.startsWith('walk')?12:p.anim==='attack'?16:p.anim==='special'?24:8)),frame=frames[loop?index%frames.length:Math.min(frames.length-1,index)],ratio=p.anim==='idle'||p.anim.startsWith('walk')?78/136:78/114;if(p.crouch&&p.ground)ratio*=.82;ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);ctx.scale((!p.anim.startsWith('walk')&&!p.anim.startsWith('jump')&&p.face<0?-1:1)*scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;if(frame.trimLeft){let left=(frame.x-frame.anchor)*ratio,right=left+frame.w*ratio,top=-frame.h*ratio,cut=left+frame.trimLeft*ratio;ctx.beginPath();ctx.moveTo(cut,top);ctx.lineTo(right,top);ctx.lineTo(right,0);ctx.lineTo(left,0);ctx.lineTo(left,top+frame.h*ratio*.7);ctx.lineTo(cut,top+frame.h*ratio*.7);ctx.closePath();ctx.clip()}ctx.imageSmoothingEnabled=false;ctx.drawImage(vazSpriteSheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,(frame.y-(frame.feet??frame.y+frame.h))*ratio,frame.w*ratio,frame.h*ratio);ctx.restore();return true}

// The Ritt sheet includes outlines and labels; source rectangles stay inside each cell.
const rittColumns=[194,334,472,609,745,880,1016,1153];
const rittColumnEnds=[332,470,607,743,878,1014,1151,1289];
function rittRow(y,h,feet){return rittColumns.map((x,i)=>({x:x+5,y,w:rittColumnEnds[i]-x-10,h,anchor:(x+rittColumnEnds[i])/2,feet}))}
const rittFrames={
idle:rittRow(17,136,152).slice(0,2),
walkRight:rittRow(168,129,296),
walkLeft:rittRow(313,131,442),
jumpRight:[{x:199,y:464,w:128,h:112,anchor:263,feet:576},{x:339,y:459,w:126,h:113,anchor:402,feet:572},{x:477,y:458,w:125,h:110,anchor:540,feet:568},{x:614,y:459,w:124,h:110,anchor:676,feet:569},{x:776,y:461,w:140,h:112,anchor:846,feet:573},{x:926,y:472,w:154,h:104,anchor:1003,feet:576}],
jumpLeft:[{x:199,y:597,w:128,h:106,anchor:263,feet:703},{x:339,y:591,w:126,h:110,anchor:402,feet:701},{x:477,y:591,w:125,h:108,anchor:540,feet:699},{x:614,y:591,w:124,h:111,anchor:676,feet:702},{x:775,y:595,w:140,h:109,anchor:845,feet:704},{x:926,y:603,w:154,h:101,anchor:1003,feet:704}],
attack:[{x:199,y:719,w:126,h:112,anchor:262,feet:831},{x:339,y:719,w:125,h:112,anchor:401,feet:831},{x:477,y:719,w:127,h:112,anchor:540,feet:831},{x:615,y:719,w:148,h:112,anchor:675,feet:831},{x:774,y:719,w:142,h:112,anchor:831,feet:831},{x:929,y:719,w:144,h:112,anchor:986,feet:831},{x:1085,y:719,w:143,h:112,anchor:1138,feet:831},{x:1239,y:719,w:137,h:112,anchor:1292,feet:831}],
special:[{x:199,y:848,w:110,h:119,anchor:253,feet:967},{x:323,y:848,w:95,h:119,anchor:368,feet:967},{x:435,y:848,w:110,h:119,anchor:484,feet:967},{x:560,y:848,w:97,h:119,anchor:607,feet:967},{x:677,y:848,w:89,h:119,anchor:718,feet:967},{x:1039,y:848,w:85,h:119,anchor:1080,feet:967},{x:1255,y:848,w:126,h:119,anchor:1310,feet:967},{x:1396,y:848,w:126,h:119,anchor:1450,feet:967}]
};
for(const name of ['jumpRight','jumpLeft','attack'])for(const frame of rittFrames[name]){frame.x+=5;frame.w-=10}
function drawRitt(p,scale){if(!rittSpriteSheet.complete||!rittSpriteSheet.naturalWidth)return false;let name=p.anim||'idle',frames=rittFrames[name]||rittFrames.idle,loop=name==='idle'||name.startsWith('walk'),fps=name==='idle'?1:name.startsWith('walk')?12:name.startsWith('jump')?8:16,index=Math.floor((p.animClock||0)*fps),frame=frames[loop?index%frames.length:Math.min(frames.length-1,index)],ratio=(name==='idle'||name.startsWith('walk')?78:76)/frame.h;if(p.crouch&&p.ground)ratio*=.82;let flip=p.face<0&&!name.startsWith('walk');ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);ctx.scale((flip?-1:1)*scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;ctx.drawImage(rittSpriteSheet,frame.x,frame.y,frame.w,frame.h,(frame.x-frame.anchor)*ratio,(frame.y-frame.feet)*ratio,frame.w*ratio,frame.h*ratio);ctx.restore();return true}
function drawSecretHero(p,scale){ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);ctx.scale((p.face<0?-1:1)*scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;let crouch=p.crouch&&p.ground,bodyTop=crouch?-45:-62;roundRect(-17,bodyTop,34,crouch?28:42,8,'#30213f','#c39aff');ctx.fillStyle='#c39aff';ctx.beginPath();ctx.arc(0,bodyTop-9,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#15101e';ctx.fillRect(-9,bodyTop-13,18,5);roundRect(-15,-20,11,20,3,'#30213f','#c39aff');roundRect(4,-20,11,20,3,'#30213f','#c39aff');if(p.anim==='attack'){roundRect(16,bodyTop+10,26,9,4,'#c39aff')}ctx.restore()}
function drawPlayer(p,h,worldAccent,scale=1){if(hero===3){if(heroLocked()&&screen!=='game')return;if(!drawElli(p,scale))drawSecretHero(p,scale);return;}if(hero===2&&drawRitt(p,scale))return;if(hero===1&&drawVazAction(p,scale))return;if(hero===0&&p.anim==='attack'&&drawBuenoNormalAttack(p,scale))return;ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h);let anim=(hero===2?rittAnimations:hero===1?vazAnimations:animations)[p.anim]||animations.idle,frame=Math.floor((p.animClock||0)*anim.fps)%anim.count,sx=anim.x+frame*anim.w+5,sy=anim.y+5,sw=anim.w-10,sh=anim.h-10,dw=anim.row>=5?84:78,dh=anim.row>=5?72:82;if(p.crouch&&p.ground){dh*=.82;dw*=1.04}let flipLeftAttack=p.face<0&&(p.anim==='idle'||p.anim==='attack'||p.anim==='special'),flipRittWalk=hero===2&&p.anim==='walkRight';ctx.scale(flipLeftAttack||flipRittWalk?-scale:scale,scale);if(p.invuln>0&&Math.floor(p.invuln*15)%2)ctx.globalAlpha=.4;let sheet=hero===2?rittSpriteSheet:hero===1?vazSpriteSheet:buenoSpriteSheet;if(sheet.complete&&sheet.naturalWidth)ctx.drawImage(sheet,sx,sy,sw,sh,-dw/2,-dh,dw,dh);else{ctx.fillStyle=h.color;ctx.beginPath();ctx.arc(0,-dh*.65,dw*.22,0,Math.PI*2);ctx.fill();roundRect(-dw*.22,-dh*.48,dw*.44,dh*.43,7,h.dark,h.color)}ctx.restore()}
function drawEnemy(e,h,accent){if(hero===2&&drawGhostEnemy(e))return;if(hero===3&&e.airborne){drawAirEnemy(e);return;}if(hero===1&&drawSnakeEnemy(e))return;if(hero===0&&drawSmallPrinter(e))return;let c=heroes[hero].color;ctx.save();ctx.translate(e.x,e.y);ctx.shadowColor=c;ctx.shadowBlur=8;roundRect(0,7,e.w,e.h-7,7,e.type===1?'#394238':'#303942',c);ctx.shadowBlur=0;roundRect(4,0,e.w-8,22,5,e.type===1?'#62726b':'#b3b9b2','#d2dedc');ctx.fillStyle='#15212a';ctx.fillRect(11,13,6,5);ctx.fillRect(e.w-17,13,6,5);ctx.fillStyle=c;ctx.fillRect(12,14,4,3);ctx.fillRect(e.w-16,14,4,3);ctx.fillStyle='#283542';ctx.fillRect(4,e.h-4,12,7);ctx.fillRect(e.w-16,e.h-4,12,7);ctx.fillStyle='#f2ede4';ctx.font='bold 11px monospace';ctx.fillText(heroes[hero].shot,e.w/2-6,38);ctx.restore()}
function drawBoss(h,accent){if(boss.kind==='specter'&&drawSpecterBoss())return;if(boss.kind==='cable'&&drawCableBoss())return;if(boss.kind==='printer'&&drawPrinterBoss())return;let b=boss;ctx.save();ctx.translate(b.x,b.y);ctx.shadowColor=heroes[hero].color;ctx.shadowBlur=b.vulnerable>0?26:13;let base=['#323c43','#24424d','#27523e'][Math.floor(level/4)];roundRect(0,17,b.w,b.h-17,18,base,heroes[hero].color);roundRect(12,0,b.w-24,37,10,'#c3c7bd','#f4dd9a');ctx.fillStyle='#17242d';ctx.fillRect(26,13,12,9);ctx.fillRect(b.w-38,13,12,9);ctx.fillStyle=heroes[hero].color;ctx.fillRect(28,15,8,5);ctx.fillRect(b.w-36,15,8,5);ctx.fillStyle='#101820';ctx.fillRect(18,b.h-14,26,15);ctx.fillRect(b.w-44,b.h-14,26,15);for(let i=0;i<3;i++){ctx.fillStyle=['#eb7468','#e9d882','#7ee5ce'][i];ctx.fillRect(35+i*18,54,11,7)}ctx.font='bold 13px monospace';ctx.fillStyle='#f3eee2';ctx.fillText(heroes[hero].shot,b.w/2-13,83);ctx.restore()}
function frame(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw()}
showTitle();requestAnimationFrame(frame);
})();
